### ISSUE TITLE
I have a question about Boomaga

### ISSUE THREAD

**Issue by Lehmeiers** [Boomaga/boomaga#104]
Hello!
I would be interested to know if Boomaga is still being developed or if it is dead.

I searched for a long time until I found a PDF printer at all.
And boomaga is really good - if it works.

Many thanks in advance.

MfG R.Lehmeier

**Comment by SokoloffA** [comment]
Unfortunately, I don't have time for this project right now. Maybe my life will change, but I can't promise anything.

I'm sorry!

**Comment by Lehmeiers** [comment]
In any case, I wish you all the best and hope that someone knows how I can get rid of error #103.
It would be a pity if I had to deinstall Boomaga. It is a great programme and has served me very well.

Sincerely R.Lehmeier
