### ISSUE TITLE
Sheet layout for stapling

### ISSUE THREAD

**Issue by robertobadjio** [Boomaga/boomaga#116]
Hello! Is it possible to make marks for stitching in the middle, on the inside of the sheet. For example, A4 format, with 1.5 - 3 - 3 - 3 - 3 - 3 - 1.5 cm? In order not to mark it all manually.

<details> 
  <summary>Photo for example</summary>

![This is an image](https://i.ibb.co/D9wzC3D/IMG-7674.png)

![This is an image](https://i.ibb.co/S7TgPsv/IMG-7675.png)
</details>

**Comment by SokoloffA** [comment]
Unfortunately I don't have enough time to support this project.
Excuse me!
