### ISSUE TITLE
Section pages count configurable

### ISSUE THREAD

**Issue by l0ddej0kk0** [Boomaga/boomaga#13]
Hi,
i'd dearly like to print 4 pages to just one bifolio section, making bigger print jobs result in multiple sections. As you can imagine, fineprint has this.
Right now, all of a print job's pages go to just one section, which when folded sticks out in the middle pages and needs to be cut additionally.
I guess the code to calculate the former is possibly even somewhat simpler than the latter; though some configuration for the section page count would have to be made accessible. Perhaps just a new option in .config/boomaga/boomaga.conf at first?
Thanks.
Apart from this, i believe that with Boomaga, you're doing great in making this concept accessible to Linux users. Keep up the good work!
p.s. I apologize for the text styling in this comment which is apparently out of my control.
-- 
regards,
-- l0ddej0kk0

**Comment by SokoloffA** [comment]
Done
