### ISSUE TITLE
 org.freedesktop.DBus.Erro.Spawn.ChildExited: Process org.boomaga exited with status 127

### ISSUE THREAD

**Issue by ktrls** [Boomaga/boomaga#22]
Hi,
after an upgrade on my KDE Manjaro distro Boomaga doesn't work.

I can see the error message in the subject when I try to print with Manjaro.
More, the Boomaga printer goes offline. If I try to switch off from printer manager, it goes down again and in the print detail I see the same error

**Comment by budinero** [comment]
Hi, I have the same problem using Arch.

**Comment by budinero** [comment]
I recompiled it with yaourt and it is working again.

**Comment by SokoloffA** [comment]
@ktrls 
Did you use the version from git? If not, I fixed this bug (I hope so).
I plan make the release soon.

**Comment by SokoloffA** [comment]
No response for long time. Closing. Feel free to reopen if you are still facing this issue.
