### ISSUE TITLE
Export to pdf is done in reversed order

### ISSUE THREAD

**Issue by Dominik3** [Boomaga/boomaga#23]
When using the export to pdf feature is boomaga the created pdf file have reversed page ordering (the last page is the first and vice versa)

Steps to reproduce:
Print a document to boomaga. (libreoffice or something else)
In boomage use file->export and save it to pdf.
When you now verify the pdf, you'll see that the page ordering is reversed.

Here is one examle with the correspondig pdf.
http://kabelfunk.de/boomaga/boom6.boo
http://kabelfunk.de/boomaga/boomaga6.pdf

**Comment by SokoloffA** [comment]
I think in your case "Reverse order" option is enabled. Please select "Print to file(PDF)" printer, and press "Configure..." button. And uncheck "Print in reverse order" checkbox.

**Comment by Dominik3** [comment]
You're right. "reverse order" was checked.
