### ISSUE TITLE
Booklet printing not duplexing

### ISSUE THREAD

**Issue by burtbick** [Boomaga/boomaga#24]
Just installed the latest 0.6.2 and am testing booklet printing.  Preview looks OK but when I print it is not duplexing.  I have selected the Printer has Duplexer option since my printer has built in duplexing.

From Adobe's Acrobat reader (Linux version) I can print booklet mode just fine with duplexing (not using boomaga).

If I print to PDF and then print the PDF file to my physical printer from Image Viewer (Linux) and specify duplex I get a properly printed booklet.

But definitely duplexing is turned off when printing booklets using the boomaga virtual ptiner.  Where should I start looking for the problem?

**Comment by SokoloffA** [comment]
Please send me your config file ~/.config/boomaga/boomaga.conf

**Comment by burtbick** [comment]
Thanks,Here's the contents of the config file:==== Start of config contents[Project]Layout=BookletDoubleSided=trueSaveDir=/home/bbick/SavedirSubBookletsEnable=trueSubBookletSize=20Printer=Samsung-ML-2150[ExportPDF]FileName=~/FooTest.pdf[Printer_Samsung-ML-2150]DuplexType=AutoBorder=falseReverseOrder=falseLeftMargin=18.0023569023569RightMargin=18.0023569023569TopMargin=36.0047138047138BottomMargin=36.0047138047138InternalMargin=14.0049831649832[MainWindow]Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x1`\0\0\0\x87\0\0\x6\x13\0\0\x3\xe8\0\0\x1h\0\0\0\xa3\0\0\x6\v\0\0\x3\xe0\0\0\0\0\0\0)State=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\0\0\0\0\xaf\0\0\x2\xed\xfc\x2\0\0\0\x1\xfb\0\0\0\x14\0\x64\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\x1\0\0\0\x39\0\0\x2\xed\0\0\x2w\0\xff\xff\xff\0\0\x3\xef\0\0\x2\xed\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)[ConfigureDialog]Width=272Height=118====== End of config contentsI've tried some different configurations, but they all result in no auto duplexing when printing to the printer.  If I print booklet to PDF file I can then print the resulting PDF file in duplex from either the Ubuntu document viewer or Adobe Acrobat (to the same printer of course).Thanks,Burt


-------- Original Message --------
Subject: Re: [boomaga] Booklet printing not duplexing (#24)

**Comment by SokoloffA** [comment]
I think I know the reason.
The boomaga uses lpr for printing. When you select manual duplex for printer, bomaga adds "-o sides=one-sided" option. So command line looks like
 
    lpr -P "Samsung-ML-2150" -# 1 -T "JobName" -o sides=one-sided  tmp_file_name.pdf

When you select "Printer has duplexer", bomaga adds no options, command line looks like

    lpr -P "Samsung-ML-2150" -# 1 -T "JobName"  tmp_file_name.pdf

Another words,  uses default options for your printer. 
I thought if a man has a duplexer, he has enabled it by default. Maybe my assumption is wrong.
Lets check my idea. Please run the following command  

    lpoptions -p Samsung-ML-2150 -l 

and look on Duplex/Double-Sided Printing line. Asterisk marked the enabled option.

For me, if I disable duplex:

    Duplex/Double-Sided Printing: DuplexNoTumble DuplexTumble *None

if I enable duplex:

    Duplex/Double-Sided Printing: *DuplexNoTumble DuplexTumble None

If I'm right, we'll think how to solve the problem.

**Comment by burtbick** [comment]
Thanks,In passing I thought about configuring duplex as default for the printer, but I wind up having to print most often single sided so I had left the printer default to no duplex.  Most of the other programs that I print with have their own "defaults" and must set the duplex option based on their default setting as they will print duplex if their default is duplex.I get the same as you when you disable duplex:Duplex/Double-Sided Printing: DuplexNoTumble DuplexTumble *NoneBurt


-------- Original Message --------
Subject: Re: [boomaga] Booklet printing not duplexing (#24)

**Comment by SokoloffA** [comment]
Standard use case for boomaga is set boomaga as default printer. You get preview for all documents, and fast option for switching duplex/single printing. So enable duplex by default looks reasonable in this case. But you are free to have your opinion.

Now I'm thinking that would be better:
 - to replace current option on 2 options "Printer has duplexer by long edge" and "Printer has duplexer by short edge"
 - or keep curent and add 2 new.

**Comment by burtbick** [comment]
Thanks I'll try it with seeing default to duplex on, and the default printer as boomagaBurt


-------- Original Message --------
Subject: Re: [boomaga] Booklet printing not duplexing (#24)

**Comment by RadicalRadish** [comment]
Thanks very much for the information here, SokoloffA. I was having the same kinds of problems as burtbrick in getting Boomaga to automatically print '1 up' as double-sided and booklets as double-sided with a printer that has automatic duplex (double-sided) printing. I followed the instructions given here:

(1) Set the printer itself to duplex.
(2) Then set Boomaga as the default printer.

Did indeed solve the problem for me of just being able to decide on single-sided or double-sided printing from inside Boomaga itself.

I really very, very much think that information should be included at the Boomaga Wiki. Some people with automatic duplex printers might try Boomaga then decide it doesn't work because this information is not in a prominent place (at the Wiki).

I would like to add that at the Wiki webpage: https://github.com/Boomaga/boomaga/wiki/Instalation There is information under the heading "Installation" that says, "Once the program has been installed, it’s time to add the virtual printer. [And so on.]" I would like to say that I didn't have to use a script or anything to get the Boomaga Virtual Printer when I installed to Linux Mint 17.2 Cinnamon Edition. As soon as Boomaga was installed it showed up in the "Printers - localhost" dialogue window.

Lastly, is it possible to make a donation to Boomaga, I'd like to say thank you for an alternative to FinePrint for Windows on Linux systems)? (Could only donate though after the Christmas/New Year period is over.)

**Comment by SokoloffA** [comment]
What about to donate me a good "Instalation" wiki page :) Send me your variant, (perhaps without formatting) and I'll post it.

**Comment by RadicalRadish** [comment]
Okay, SokoloffA - I'll give that a go, but you'll have to give me some time.

**Comment by RadicalRadish** [comment]
Hi Alexander,

Okay I'll give that a try. Might take me a couple of days though. I'm a total newbie to Linux and am using Linux Mint Cinnamon Edition. On that basis any install guide that I manage to write will be quite simple - which might actually suit a lot of people.

Would you mind if asked why is it the case that Boomaga is not included in the official repositories for Linux Mint? It's a very good and very useful utility and I can't think of any reason why it's not available for users to easily install on a system.

Peter


On 09/12/15 16:56, Alexander Sokolov wrote:

What about to donate me a good "Instalation" wiki page :) Send me your variant, (perhaps without formatting) and I'll post it.

**Comment by SokoloffA** [comment]
> I'm a total newbie to Linux 

This can be an advantage. Bearded guru can skip some thing that obvious for him, but it can cause problems for normal users. A good example is this thread, I'm the author and duplex enabling  is obvious to me, but not for users.


> Would you mind if asked why is it the case that Boomaga is not included in the official repositories for Linux Mint? 

There are no special reasons. The program has no tricky dependencies or other blocking things. 

There are many Linux distributions. I don't use Linux Mint, for my distro I wrote a package and he was in the main package base. Unfortunately, I have no time to promote the program to all distributions. I think this is a good example where the OpenSource community can show its force, the programmer improves the program code, and maintainers creates packages for distributions. 
And yet, the promotion package, it's more social work than technical, I'm not a very social person.

**Comment by RadicalRadish** [comment]
Hello Alex,

Here is my attempt at installation instructions. Please read it and see if they are okay. It kind of grew as I realised how many instructions I had to include for a newbie to able to install and do an initial test of Boomaga. In particular I am not sure if my instructions for "(4) Manual Double-Sided Printing from Within Boomaga" are actually correct - I don't have to do this for my automatic duplex printer so I was just guessing what the owner of a manual duplex printer would have to do to configure and test Boomaga for such a printer.

If there is anything really wrong with the instructions let me know I'll have a go at redrafting the relevant sections. Maybe you could email the document back to me with comments and I could then see if I could improve it a bit according to your comments.

Oh! I just found out that I can't post an 'odt' document here at GitHub. Had to post the doc as 'docx' type.
[Installing Boomaga (Draft 1).docx](https://github.com/Boomaga/boomaga/files/59594/Installing.Boomaga.Draft.1.docx)

**Comment by SokoloffA** [comment]
Sorry for delay. I was sick and then the New Year holidays. 
Thanks for article. I posted it on wiki. I split your article on 2 parts. I thought it's too big, also the second part can be useful for users of other distributions.
 
* [https://github.com/Boomaga/boomaga/wiki/How-to-Install-Boomaga-in-LinuxMint-or-Ubuntu](How to Install Boomaga in LinuxMint or Ubuntu)
* [https://github.com/Boomaga/boomaga/wiki/Things-To-Do-After-Installing-Boomaga]([Things To Do After Installing Boomaga)

**Comment by RadicalRadish** [comment]
Thanks and glad you think them useful, Alex. Hope they help others. However, the two links you provide don't work - page not found errors. I'll try myself:

https://github.com/Boomaga/boomaga/wiki/How-to-Install-Boomaga-in-LinuxMint-or-Ubuntu
https://github.com/Boomaga/boomaga/wiki/Things-To-Do-After-Installing-Boomaga

**Comment by RadicalRadish** [comment]
This isn't an 'issue' just a question for something that I don't understand about Boomaga.

By my newbie understanding CUPS is a printer driver. On Linux most printers will be using CUPS to interface with the printer and manage the printing of a document. However, some people using Linux do manage to get a hold of and install printer drivers from the printer manufacturers - so I'll call these printer drivers "manufacturer printer drivers".

My question is does Boomaga only work when the user is using CUPS printer drivers? Or does Boomaga also work if the user is using manufacturer printer drivers?

**Comment by SokoloffA** [comment]
No CUPS isn't a printer driver. It's printing system, it's includes daemon and drivers for most popular printers. All modern distributives use CUPS as standard printing system. "Manufacturer printer drivers" is a drivers for CUPS. Boomaga adds another one printer to CUPS. 

Workflow looks like:

1. You click "print" button in your application. 
2. Application send print job for Boomaga printer to CUPS.
3. CUPS run boomaga backend driver
4. Boomaga backend driver starts GUI Boomaga application
5. You click "print" button in the boomaga GUI
6. Boomaga GUI sends print job for your hardware printer to CUPS
7. CUPS send job to hardware printer.

**Comment by SokoloffA** [comment]
In short, yes Boomaga work if the user is using manufacturer printer drivers.

**Comment by RadicalRadish** [comment]
May thanks for the response. I think I have better idea of how it works now. :)
