### ISSUE TITLE
Paper Size Options

### ISSUE THREAD

**Issue by Notsonoble** [Boomaga/boomaga#30]
As someone who's done a bit of booklet printing, there's a few advantages to some of the other paper sizes. Part of the reason I found boomaga is I was looking to reduce my need for a windows vm. 
US Legal makes a good booklet print size for something originally formatted in US letter. Also, I have a wideformat hp (up to 13''x19'') 11''x17'' prints booklets where each "page" is US letter.

Is this something you've considered?

**Comment by SokoloffA** [comment]
You can use it right now. Using the standard printer settings dialog of your operating system.

1. For the boomaga printer set the paper type to Letter. 
2. For the real printer through which you will print, set the paper type to Legal.

Or I don't understood you.
