### ISSUE TITLE
Ubuntu 16.04 Xenial build

### ISSUE THREAD

**Issue by mikhailnov** [Boomaga/boomaga#34]
Please build boomaga for Ubuntu 16.04 Xenial in your PPA. Thank you.

**Comment by mikhailnov** [comment]
I see that a Debian packaged was merged into ubuntu 16.04 repos. But still a build from the author would be nice to have an always up-to-date version.

**Comment by SokoloffA** [comment]
I'll do it soon.

2016-03-26 16:10 GMT+03:00 mikhailnov <notifications@github.com>:

> I see that a Debian packaged was merged into ubuntu 16.04 repos. But still
> a build from the author would be nice to have an always up-to-date version.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Boomaga/boomaga/issues/34#issuecomment-201818716>
>



-- 
Best regards,
Alexander.

**Comment by SokoloffA** [comment]
Done
