### ISSUE TITLE
Rosa repository GTK 

### ISSUE THREAD

**Issue by mikhailnov** [Boomaga/boomaga#35]
Why do you use a GTK version of Boomaga in ROSA repos? You already have a Qt5 version of Boomaga, Qt5 has already been fully integrated into ROSA 2014.1, KDE is ROSA's main DE and a Qt5 version will be more native. Especially the file open dialog.

**Comment by SokoloffA** [comment]
Boomaga has no GTK version at all. Boomaga has Qt4 and Qt5 versions. I'm use Qt4 for Rosa because:

1. KDE4 is more popular than KDE5. IMHO reasonable to have Qt4 programs in KDE4. 
2. Qt5-KDE4 integration has some lacks now.
