### ISSUE TITLE
Booklet imposition...

### ISSUE THREAD

**Issue by jumaxotl** [Boomaga/boomaga#37]
Not really an issue but more like two little requests...

Is there any plan of correcting the the booklet option which currently generates reader's spreads instead of proper printer's spreads ?!

Also I would very much love to have the ability to define a negative internal margin order to handle bleed ?

Cheers,

Julien

**Comment by SokoloffA** [comment]
I don't understood you exactly, can you explain your requests. Perhaps with examples.

**Comment by jumaxotl** [comment]
Ok...

So at the moment when selecting the booklet option the pages are shown on screen as they will eventually will appear to the reader, meaning pairs of facing pages are shown side-by-side ; for example if you have 8 pages, page 1 shows on its own, then pages 2 and 3 together, 4 and 5 together, and so on up tp page 8 which also shows on its own...
![readers-vs-printers-spread-1-300x300](https://cloud.githubusercontent.com/assets/12113429/15140394/2458347e-169b-11e6-8365-f55f461a1371.jpg)

But in order to make and print the booklet the pages need to be reordered and paired as a printer's spread, meaning pages 8 and 1 together, 2 and 7 together, 6 and 3, and so on...

![readers-vs-printers-spread-1-300x300](https://cloud.githubusercontent.com/assets/12113429/15140379/18119ca0-169b-11e6-89ee-818f9d604e4a.jpg)


About the bleed...

Sometimes you may want to have a picture bleeding of the page, meaning it's printed right up to the edge of the page, and in order to achieve this you need the image to be placed beyond the edge of the printed sheet before trimming. So there's no problem really with pdf files which are composed with a bleed, except when you need to make a booklet because then the bleed needs to be removed along the folding line - it's the middle of the sheet where the pages are rearranged together and which is usually just the inner margin, but it becomes an issue when you want to have a double-spread image for example.

![bleed and inner margins](https://cloud.githubusercontent.com/assets/12113429/15140941/c8f8eabc-169d-11e6-9223-20307c0a8995.png)

So this is it... Let me just add to this that Boomaga is otherwise doing a fantastic job and needless to say those two features would make it almost perfect ! :)

**Comment by jumaxotl** [comment]
**Correction :** I've only just noticed the page rotation option for the input files so that answers my question about the printer's spread and it works perfectly : I'm sorry I should have read the manual :)

**Comment by SokoloffA** [comment]
**About spread.**
> page 1 shows on its own, then pages 2 and 3 together, 4 and 5 together, and so on 

It's only preview. For really printing boomaga send pages with "printer's" order (8 and 1 together, 2 and 7 together, 6 and 3).


**About margins**
For tests you can set negative margins manually in config file. Edit ~/.config/boomaga/boomaga.conf and change line like

```Profiles\XX\InternalMargin= ```

where XX is a number of appropriate printer profile.

If it's help you I'll add such feature in the next releases.

**Comment by jumaxotl** [comment]
Ok thanks for the suggestion but it still doesn't work even when manually editing boomaga.conf with a negative value for the internal margins...

**Comment by SokoloffA** [comment]
Boomaga isn't a real publisher program, it's a printer wrapper for everyday using by "standard" users. 
If you need a complex layout, and you want to accurately track the position of objects on the page, IMHO have sense for you to use a real publishing program like Scribus.

**Comment by jumaxotl** [comment]
Well... Don't underestimate the qualities of your program because it's nearly perfect : my printer never complains about the files I'm sending and, like I said it's only lacking a very few options in order to be able to do a full imposition, but still it's undoubtedly great at handling simple jobs !

As for Scribus, of course I'm using it on a daily basis but so far implementing imposition is only a proposal (https://wiki.scribus.net/canvas/Imposition_proposal) and it doesn't look like it's going to be any time soon so, again, the best option I have found yet is Boomaga because, unlike many others I've tried, it does the job well and it is user-friendly. Of course you could argue that there are a lot of non-free and closed-source options out there, mainly provided Adobe and alikes, but this is where I come from originally and I'm not at all considering to go back (and neither is my printer btw) so I guess we just have to be patient and wait for the right thing to come whenever it's ready :)

But anyway, thanks a lot for your time and efforts, they are greatly appreciated.

Cheers,
