### ISSUE TITLE
Boomaga not showing up in printer list in Linux Mint 17.1 64bit

### ISSUE THREAD

**Issue by burtbick** [Boomaga/boomaga#38]
Been using Boomaga for a while on a 32 bit installation of Ubuntu 12.04.  Finally got around to upgrading to 64 bit Linux Mint 17.1 Installed Boomaga from the PPA, no obvious errors during the installation but Boomaga is NOT showing up in the printers as it did in the 32 bit installation.

What might I have missed during the installation?  Is there a dependency that may be missing?

Note my other printers all show up as expected.  Just Boomaga is missing in action.

**Comment by SokoloffA** [comment]
What version of LinuxMint you are using,  Cinnamon, KDE, MATE, Xfce?

**Comment by burtbick** [comment]
Thanks, I'm running Mint 17.1 Cinnamon..  But it looks like it resolved itself.  I just uninstalled Boomaga and re-installed it and this time it installed Boomaga as a virtual printer, and it is up and working.  Not sure why it didn't install the Boomaga virtual printer in the printers list the first time, but it did it on the reinstall.

I have two other Mint 17.1 boxes that I'll be installing Boomaga on and if the problem repeats with those installations I'll post another new issue with more details.
