### ISSUE TITLE
Cannot see the lower part of the window

### ISSUE THREAD

**Issue by MurKit** [Boomaga/boomaga#40]
I am using Linux Mint 17.3. Cannot resize the window of Boomaga to fit my 1366*768 display by height.
So I cannot see bottom of the preview pages and the strings "Sheet xx of xx   xx pages (xx sheets).
Also Maximize window button does nothing.

**Comment by carsonip** [comment]
I use Linux Mint 18. The Maximize window button works well for me.

**Comment by SokoloffA** [comment]
No response for long time. Closing. Feel free to reopen if you are still facing this issue.
