### ISSUE TITLE
Print copies collated

### ISSUE THREAD

**Issue by hungryseashell** [Boomaga/boomaga#44]
First of all mad props to this project, really awesome.

As a casual user of boomaga I had a very hard time finding how to print multiple copies of the same booklet. (And with the least amount of manual interaction with the printer as I have no duplexer on it)

After experimenting a lot with boomaga I found the 'print with options...' in the menu where the only option is to set the number of copies.

It works fine, the only issue is that the papers come out from the printer uncollated.

**So I have two suggestions:**
1. Add an option to print the multiple copies collated
2. Make some UI changes so new users can find the 'print with options' more easily. Maybe just add it to the toolbar.

**Comment by SokoloffA** [comment]
@hungryseashell 
1. I added the option "collate copies".
2. About changing UI. It is not very frequently used option, and I don't want to clutter up the panel, we laready have 2 print buttons. But I'll think about it.

**Comment by hungryseashell** [comment]
Thank you for the fast response! Collating copies are working well now.

An other thing. I built boomaga on ubuntu 16.10 and it would always stop during make due to missing `poppler/PDFDoc.h`.
I needed to install `libpoppler-private-dev` to make a succesful build.
Maybe you can add this to the wiki.

**Comment by SokoloffA** [comment]
> Maybe you can add this to the wiki.

Done
