### ISSUE TITLE
install Printer error

### ISSUE THREAD

**Issue by temudschin** [Boomaga/boomaga#45]
After successfull Compilation and Installation on Centos 7 (boomaga binary runs fine), I tried to install the boomaga printer using the script installPrinter.sh.

Running this script results in an error: lpadmin: Bad device-uri scheme "boomaga".

Looks like lpadmin does not like -v boomaga:/ option.

Any ideas, what I can do?

**Comment by SokoloffA** [comment]
It seems that CUPS can't find the boomaga backend file (/usr/lib/cups/backend/boomaga). 

1. Should exists **/usr/lib/cups/backend/boomaga** file. Pay attention, not /usr/local, and not /usr/lib64/
2. It permission should be a 700 (rwx------)

Perhaps you should to restart cups daemon.

P.S.
This issue #43 is not directly related to the your problem, but it may be of usable for you.

**Comment by temudschin** [comment]
Thanks for the help, that worked. Afterwards I had to manually copy booma.ppd to /usr/share/ppd/boomaga/ so that lpadmin does not throw the error "Unable to copy ppd file", when running the installPrinter.sh script. Finally I linked the file org.boomaga.service (I installed boomaga in /opt) to /usr/share/dbus-1/services/ as mentioned in #43. 

Now it works, thanks a lot!
