### ISSUE TITLE
remove white margins

### ISSUE THREAD

**Issue by femifrak** [Boomaga/boomaga#47]
I have got a pdf in A5 format (14.8 cm x 21 cm) which was centered on A4 pages (21 cm x 29.7 cm). That means there are large margins at the sides and on top and bottom (additionally to the margins of the A5 document). I like the possibility of Boomaga to adjust the margins, however, I am not able to set negative values. Is it possible to decrease the margin width / to enlarge the printed area?
Thanks, Femi

**Comment by SokoloffA** [comment]
I'll add this feature in the next release. But as an option, you will need to enable it in the preferences dialog.

**Comment by SokoloffA** [comment]
Done. https://github.com/Boomaga/boomaga/commit/b495615ab0169729efb55fe45be95d5f8f2f8b03
