### ISSUE TITLE
Cannot select color printing

### ISSUE THREAD

**Issue by vkasala** [Boomaga/boomaga#48]
Hi,

I have a problem with CUPS printers on Linux/Ubuntu 16.04. When I am printing, I get always Black & White document, because that's the default of the printer. Can I do it somehow?

Thanks.

**Comment by SokoloffA** [comment]
What printer you are use? Try following:

1. Copy ppd file for your hardware printer from /etc/cups/ppd directory to somewhere as gray.ppd.
In the GUI config change settings to color.
2. Copy ppd as color.ppd
3. Send me these files.

**Comment by SokoloffA** [comment]
I added "Force color" mode to profile. https://github.com/Boomaga/boomaga/commit/ce9dc7aa808ee5e1bcd5e75e9c8fd5a1d1ed8913
