### ISSUE TITLE
Feature Request: Print and Save

### ISSUE THREAD

**Issue by Nuube** [Boomaga/boomaga#49]
I really like this program and use it as standard printer, but I am missing some features from a tool I used on M$ platform before. It would be nice if they can be added. 

A simple feature but turned out useful to me is to save the printjob on disk after printing. It turned out in the past  quite useful e.g. when you printing an webpage it gets archived that way.

Since a print into file as  pdf is already available (I am actually not sure if this is a Boomaga feature or a pdf-printer coming with my Mint installation), it would be nice if this would be not either-or but a both-at-the-same-time option available. 

The save filename should be automagically generated if possible, so the archiving is done in completly background.

**Comment by SokoloffA** [comment]
I'll add this feature in the next release. But as an option, you will need to enable it in the preferences dialog.

**Comment by SokoloffA** [comment]
Done https://github.com/Boomaga/boomaga/commit/b495615ab0169729efb55fe45be95d5f8f2f8b03
