### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Boomaga/boomaga#51]
Please, add any option so we can print multi pages in the same page, and a booklet from right to left direction.

and thank your for this amazing program. It's a life saving.

**Comment by SokoloffA** [comment]
I apologize for the long silence, I'm on vacation now. And have some problems with the Internet.
I have 2 questions:
1. You mean the standard booklet but with the opposite order of the pages? 
2. If job has 3 pages, then in the booklet will be one blank page. In your case this blank page should be the leftmost or rightmost?

**Comment by ahmed-elsayed2017** [comment]
Sorry, I didn't know that you answered me.

I mean books in western language, people open it from the left side, but in other language written from right to left (like Arabic), you open the book from the other side (the right side).

So when you print a booklet you need to print in the reverse direction, which means the first page in an English book will be last page in an Arabic book.

**Comment by SokoloffA** [comment]
How pages should be printed If the sheet is not filled in completely? 

For example, we have a document on 5 sheets and use "8 up horizontal" layout.
For Left-to-Right, the position of the pages will be as follows:
```
...........................
. +---+ +---+ +---+ +---+ .
. | 1 | | 2 | | 3 | | 4 | .
. |   | |   | |   | |   | .
. +---+ +---+ +---+ +---+ .
. +---+                   .
. | 5 |                   .
. |   |                   .
. +---+                   .
...........................
```



How should it look for Right-to-Left?

**Comment by ahmed-elsayed2017** [comment]
I took some pictures from my printer configuration that support right-to-left layout.

![1](https://user-images.githubusercontent.com/29783425/37362804-e91995f8-26fe-11e8-8f5a-754cfb74d611.png)
![2](https://user-images.githubusercontent.com/29783425/37362805-ea0c76c4-26fe-11e8-95f8-26bb37eb77e9.png)

**Comment by SokoloffA** [comment]
I added support for the right-to-left directions in the "[right-to-left](https://github.com/Boomaga/boomaga/tree/right-to-left)" branch. It would be great if you would test this version. You can change the direction on the preferences page.
If you have skills you can clone *right-to-left* branch and to build the project from sources:
```
git clone https://github.com/Boomaga/boomaga.git --branch right-to-left boomaga
cd boomaga 
mkdir build 
cd build 
cmake 
make 

gui/boomaga
```
If you haven't such skill, say me what distro you are use I try to build program for you.


I also have a few questions.
1. Should I change the icons on the *"Previous sheet"* and *"Next sheet"* buttons.
2. Should I change the direction of scrolling on the mouse. 

Write me what else I need to change.

**Comment by ahmed-elsayed2017** [comment]
Ok. Thanks, I will try it.

**Comment by ahmed-elsayed2017** [comment]
cmake  ended with an error

`CMake Error at CMakeLists.txt:29 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/ahmed/boomaga/build/CMakeFiles/CMakeOutput.log".
See also "/home/ahmed/boomaga/build/CMakeFiles/CMakeError.log".
`
I'm using Linux Mint 18.3.

**Comment by ahmed-elsayed2017** [comment]
[CMakeError.log](https://github.com/Boomaga/boomaga/files/1826938/CMakeError.log)
[CMakeOutput.log](https://github.com/Boomaga/boomaga/files/1826939/CMakeOutput.log)

**Comment by ahmed-elsayed2017** [comment]
I'm using Linux Mint 18.3.

**Comment by SokoloffA** [comment]
You need to install the dependencies. Please run the following command:
```
apt install debhelper dpkg-dev cmake qtbase5-dev qttools5-dev-tools qttools5-dev libcups2-dev libsnappy-dev libpoppler-cpp-dev
```
[This article](https://github.com/Boomaga/boomaga/wiki/Instalation-from-sources) may also be useful.

Today later I'll install Mint in Virtualbox and build the program for you.

**Comment by ahmed-elsayed2017** [comment]
I installed the dependencies, and I could build and run it without any problems.

I will test it, and give you the result later.

**Comment by ahmed-elsayed2017** [comment]
I printed a booklet, and it was flawless (with right to left direction turned on).

I'm going to try 8 pages in 1.

**Comment by ahmed-elsayed2017** [comment]
Everything is working without any problem.

Booklet / Multi pages / Next sheet and previous sheet buttons works fine.

When I scroll up it goes to the next sheet, and when I scroll down it goes to the previous sheet. I don't know how it suppose to work, and it doesn't matter for me.

Finally I don't have to switch between Windows and Linux to use my printer.

Thanks man for your efforts, it's really appreciated, and thanks for this life-saving application.

**Comment by SokoloffA** [comment]
What about the icons on the "previous page" and "next page" buttons? For me it looks like:
![screenshot_20180320_143653](https://user-images.githubusercontent.com/854935/37652480-b0a088c8-2c4c-11e8-861a-325faa208177.png)
Should I swap the icons?

**Comment by ahmed-elsayed2017** [comment]
For me, it looks like in this picture

![screenshot from 2018-03-20 15-52-59](https://user-images.githubusercontent.com/29783425/37658707-d53f8fd0-2c56-11e8-8bf6-1cc72c2effc1.png)

It's odd for me to be swapped like in your picture.

Actually all the programs translated into right-to-left languages like Arabic, all the windows and panels are swapped, and that because of the way the letters are written, and that's why I use all the programs in English to looks how it should be.

**Comment by ahmed-elsayed2017** [comment]
I'm sorry for asking this. Are you planning to add right-to-left layout to the main branch in the future or it's going to be a sub branch?

**Comment by SokoloffA** [comment]
Qt contains right-to-left language support.  It automatically rotates menus and toolbars for some languages. I started the program with a right-to-left LANG environment variable.
```
LANG=ar_AE ./gui/boomaga
```

My idea is - if the interface language is right-to-left, I need to swap the icons on the navigation buttons. If the interface language is left-to-right, the interface remains as-is. Is this correct?

**Comment by ahmed-elsayed2017** [comment]
Oh! you are right about this, it's a great idea. :+1:

**Comment by SokoloffA** [comment]
>Are you planning to add right-to-left layout option to the main branch 

Done https://github.com/Boomaga/boomaga/commit/d67d1501554a4170fa33b3b297d69892a0eb647f

**Comment by ahmed-elsayed2017** [comment]
I'm so happy. Thank you man, and sorry for taking so much time to answer you when you answered me in the first time.

**Comment by SokoloffA** [comment]
I'm glad.

I have a question about my other program. There is a program [flacon](http://flacon.github.io/index.html), it contains a button "Convert".
![screensot](http://flacon.github.io/screenshots/flacon-main.png). Should I change it for Right-to-Left languages?

**Comment by ahmed-elsayed2017** [comment]
No, it's ok.

I actually need a program like falcon.

**Comment by ahmed-elsayed2017** [comment]
I can translate these applications to Arabic if you want.

**Comment by ahmed-elsayed2017** [comment]
No, I think it's ok.

**Comment by ahmed-elsayed2017** [comment]
You didn't add right to left support in the main repository, and every time I try to compile from the source as I did before in Linux Mint, I get an error.

And in the last version,  I have to rotate the papers before I continue printing on the other side of the paper, otherwise the even pages will be different from the odd pages.

**Comment by ahmed-elsayed2017** [comment]
![error](https://user-images.githubusercontent.com/29783425/39158086-61c92796-475e-11e8-98d7-f9de904c76bf.png)

[CMakeError.log](https://github.com/Boomaga/boomaga/files/1940339/CMakeError.log)
[CMakeOutput.log](https://github.com/Boomaga/boomaga/files/1940340/CMakeOutput.log)

**Comment by ahmed-elsayed2017** [comment]
@SokoloffA 
[CMakeError.log](https://github.com/Boomaga/boomaga/files/1940339/CMakeError.log)
[CMakeOutput.log](https://github.com/Boomaga/boomaga/files/1940340/CMakeOutput.log)

**Comment by SokoloffA** [comment]
@ahmed-elsayed2017 
As I said, R-to-L support is in the master branch. So clone repo like:
```git clone https://github.com/Boomaga/boomaga.git boomaga```

>And in the last version, I have to rotate the papers before I continue printing on the other side of the paper, otherwise the even pages will be different from the odd pages. I think it's a new bug that doesn't exist before.

I don't understand if you don't have a compiler which version you're testing.  Please build program from master and test it. If the problem persists, let me know the details.

Or wait a bit, I'll release a new version this week.

**Comment by ahmed-elsayed2017** [comment]
@SokoloffA 
I compile the program like this : 

> sudo apt install -y debhelper dpkg-dev cmake qtbase5-dev qttools5-dev-tools qttools5-dev libcups2-dev libsnappy-dev libpoppler-cpp-dev
> sudo apt install -y git
> git clone https://github.com/Boomaga/boomaga.git --branch right-to-left boomaga
> mkdir ~/boomaga/build
> cd ~/boomaga/build
> cmake ..
> make && sudo make install

And I get the error I've told you about before.

**Comment by SokoloffA** [comment]
I haven't released the program in a long time. I'll make a release this week.

**Comment by SokoloffA** [comment]
I made release.

**Comment by ahmed-elsayed2017** [comment]
Ok. Thanks.

**Comment by ahmed-elsayed2017** [comment]
Right-to-left exist in the new version.

 The same thing happens when printing with double-sided option :

[jpg.jpg.pdf](https://github.com/Boomaga/boomaga/files/1948787/jpg.jpg.pdf)

If I print 2 pages with number 1, and number 2 will look like what is in this picture, so when I finish even pages, I have to rotate the pages 180 degrees before I press continue to print the even pages.

Look at this picture. There are 128 pages in this book. In sub-booklet there are also 128 pages, so sub-booklet doesn't help dividing the book into sub-booklets.

![screenshot from 2018-04-25 22-44-15](https://user-images.githubusercontent.com/29783425/39272154-68b4ac46-48db-11e8-8701-1f6411e5411c.png)

**Comment by SokoloffA** [comment]
Confirm the bug with the rotation of two-sided documents. I will fix it. 

About "128 pages" the program divides the document into sub-booklets only when you print the book ("Booklet" layout)

Please create separate issues for different problems.

**Comment by davidhwchong** [comment]
Boomaga currently prints odd pages first followed by even pages. Is there a way to make it print the even pages first? I need this for my Brother printer so that the completed duplex printing will be sorted correctly. I currently have to flip each page around to get the right order after printing.
