### ISSUE TITLE
PDF-export A4 default with no apparent way to select Letterpaper.

### ISSUE THREAD

**Issue by timtro** [Boomaga/boomaga#58]
Thank you for a fantastic piece of software in Boomaga.

Living in Canada, I'm cursed with US letter paper requirement. For some reason, Boomaga doesn't duplex properly with my printer, so I have been doing a pdf export and printing with Evince. I noticed that sometimes my outer edges would get clipped. While trying to figure out why, I noticed that Evince reports a4 paper size on the pdf. I'm guessing that pdf-export defaults to a4. If that is indeed the case, is there a way for me to work around this?

Thanks for all your time and effort.

**Edit:** I know that I can fiddle with the margins and then set "fit to page" when printing from Evince, but when I say workaround, I mean something that produces the same output as native US letter paper support.

**Comment by SokoloffA** [comment]
When you print to the printer workflow looks like this:
```
+-------------------------------+
|   The initial program.        |     Step 1
|   browser, text editor, e.t.c |
+-------------------------------+
        ↑            ↓
      Papper     PDF file for
       size      paper size 
        ↑            ↓
+-------------------------------+
|    CUPS driver for boomaga    |     Step 2
+-------------------------------+
              ↓
         PDF file for
          paper size
              ↓
+-------------------------------+
|         Boomaga GUI           |     Step 3
+-------------------------------+
       ↓              ↓
      PDF            PDF
      file           file
       ↓              ↓
+-----------+     +-----------+
| Hardware  |     |  Export   |     Step 4
| printer   |     |  to PDFe  |
+-----------+     +-----------+
```
Only the initial program on step 1 can properly reformat the document with a different paper size. For example, wrap a line on a different place, move image to next page, and so on. 

On step 2 program just passes the file to step 3.

On step 3 program takes already ready Postscript/PDF file, and can only scale the document and add an empty fields at the edges. 

By default, when package manager adds the virtual printer it set A4 for it. You need in the printer settings to change the size to US letter. So, from step 1 all documents will have letter size.




.
>For some reason, Boomaga doesn't duplex properly with my printer 

What reasons? This is a bug in the boomaga or something else?

**Comment by timtro** [comment]
Thank you for your very well executed explanation. You were quite correct: my printer configuration on my laptop was set to default to A4, and must have been for weeks without me noticing. I was so focused on Boomaga's configuration, I completely took for granted that my own printer was configured properly.

**Comment by carafelix** [comment]
Hello @SokoloffA, I think it would be nice to add an option to change the virtual pdf paper size.

I'm using boomaga to export to pdf, and... since it uses, if I am correct, my printer config to construct the virtual pdf, I need to config the paper size on the printer, re-open boomaga and just once that is done I can play with a different virtual paper size. That is even more troublesome if the size I want is not available on the printer default settings... that must be added, etcetc.

I want to give this pdf to the publisher in the publisher terms, and not print exactly on my own printer.

This is important since non-matching papersize add margins and such

Please re-open this issue.
