### ISSUE TITLE
error: "[Boomaga] Can't extract D-Bus bus address for user "root" and session """

### ISSUE THREAD

**Issue by ktrls** [Boomaga/boomaga#65]
Hi, I'm not able to use boomaga from one year 'cause the problem of poppler.

Yesterday I have installed the new version with the fix (now I have the 1.0.0.1 version) on my Manjaro distro, so I tried to use it, but it doesn't work :(

When I try to print the test page I have an error. Using diagnostics tool I see the error in the subject.

Can you help me?

**Comment by SokoloffA** [comment]
View logs of CUPS, maybe you'll find information that will clarify the situation.

run run under root
```/usr/lib/cups/backend/boomaga 123 ktrls "title" 1 "" pdf_file.pdf```
where: 
* 123 - print job ID, any number
* ktrls - your login
* title - print job title, any string
* 1 - number of copies
* pdf_file.pdf - existing file name

example output
```
[root@sokoloff-work tests]# /usr/lib/cups/backend/boomaga 123 sokoloff "title" 1 "" 01-pages.pdf
DEBUG: [Boomaga root] run boomagabackend as UID:1000 GID: 1000
DEBUG: [Boomaga] Start boomagabacked '/usr/local/lib/boomaga/boomagabackend', '123', 'title', '1', ''
INFO: [Boomaga] jobId:   123
INFO: [Boomaga] title:   title
INFO: [Boomaga] count:   1
INFO: [Boomaga] options:
INFO: [Boomaga] uid:     1000
INFO: [Boomaga] user:    sokoloff
INFO: [Boomaga] home:    /home/sokoloff
DEBUG: [Boomaga] xDisplay: :0
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/1263/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/1308/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/5398/environ"): device not open
DEBUG: [Boomaga] exe name bash
DEBUG: [Boomaga] D-Bus address unix:path=/run/user/1000/bus
DEBUG: [Boomaga] Cache dir: /home/sokoloff/.cache
DEBUG: [Boomaga] Job files: /home/sokoloff/.cache/boomaga_in_file_123[01].pdf
DEBUG: [Boomaga] Start boomaga: '/home/sokoloff/.cache/boomaga_in_file_123[01].pdf' 'title' 'true' '' '1'
```

---

In your message, there are 2 oddities. 
1. _for user "**root**"_ - why the program search a session for root. Is you start X under root? 
2. _and session **""**_ - The second quotes should contain the number of the XDisplay (like ":0"),  it is empty in your case. But if the program not found xDisplay, the program must be interrupted before this message.

**Comment by ktrls** [comment]
Hi Alexander,

the answer of your question 1. is that "root" is the user on CUPS with administration access on it

I have made your test and this is the output

`[ktrls@pohl ~]$ sudo /usr/lib/cups/backend/boomaga 666 ktrls "test Boomaga" 1 "" tuscia.csv 
DEBUG: [Boomaga root] run boomagabackend as UID:1000 GID: 1000
DEBUG: [Boomaga] Start boomagabacked '/usr/lib/boomaga/boomagabackend', '666', 'test Boomaga', '1', ''
INFO: [Boomaga] jobId:   666
INFO: [Boomaga] title:   test Boomaga
INFO: [Boomaga] count:   1
INFO: [Boomaga] options:
INFO: [Boomaga] uid:     1000
INFO: [Boomaga] user:    ktrls
INFO: [Boomaga] home:    /home/ktrls
DEBUG: [Boomaga] xDisplay: :0
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/2802/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/2805/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/2908/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/2914/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/2917/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/2945/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/2979/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3098/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3112/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3140/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3150/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3201/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3250/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3291/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3319/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3364/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3380/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3419/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3437/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3474/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3494/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3510/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3542/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3558/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3588/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3603/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3613/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3670/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/3702/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/6425/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/6490/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/6700/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/7104/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/974/environ"): device not open
WARNING: [Boomaga] QIODevice::read (QFile, "/proc/984/environ"): device not open
DEBUG: [Boomaga] exe name dbus-daemon
DEBUG: [Boomaga] D-Bus address unix:path=/run/user/1000/bus
DEBUG: [Boomaga] Cache dir: /home/ktrls/.cache
ERROR: [Boomaga] Unknown format of input file`

this is actual content in the cups error_log (but I don't see anything about the test above):

`E [23/Nov/2017:09:01:01 +0100] Missing value on line 2257 of /var/cache/cups/job.cache.
E [23/Nov/2017:09:01:01 +0100] Missing value on line 2402 of /var/cache/cups/job.cache.
E [23/Nov/2017:09:36:50 +0100] [cups-deviced] PID 5951 (gutenprint52+usb) stopped with status 1!
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/1499/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/1510/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/3962/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/3965/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4068/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4078/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4213/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4224/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4255/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4270/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4286/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4291/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4319/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4393/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4422/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4457/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4514/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4531/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4548/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4561/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4599/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4619/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4646/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4655/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4678/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4704/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/4724/environ\"): device not open
W [23/Nov/2017:09:37:23 +0100] [Job 295] [Boomaga] QIODevice::read (QFile, \"/proc/5841/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/1499/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/1510/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/3962/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/3965/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4068/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4078/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4213/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4224/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4255/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4270/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4286/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4291/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4319/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4393/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4422/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4457/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4514/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4531/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4548/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4561/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4599/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4619/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4646/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4655/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4678/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4704/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/4724/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 296] [Boomaga] QIODevice::read (QFile, \"/proc/5841/environ\"): device not open
W [23/Nov/2017:09:37:24 +0100] [Job 297] [Boomaga] Can\'t found active session for user \'root\'.
E [23/Nov/2017:09:37:24 +0100] [Job 297] [Boomaga] Can\'t extract D-Bus bus address for user \"root\" and session \"\"
E [23/Nov/2017:09:37:56 +0100] [cups-deviced] PID 6094 (gutenprint52+usb) stopped with status 1!
W [23/Nov/2017:09:38:07 +0100] CreateProfile failed: org.freedesktop.ColorManager.Profile.Internal:failed to register object: An object is already exported for the interface org.freedesktop.ColorManager.Profile at /org/freedesktop/ColorManager/profiles/Boomaga_printer_Gray__
W [23/Nov/2017:09:38:07 +0100] CreateProfile failed: org.freedesktop.ColorManager.Profile.Internal:failed to register object: An object is already exported for the interface org.freedesktop.ColorManager.Profile at /org/freedesktop/ColorManager/profiles/Boomaga_printer_CMYK__
W [23/Nov/2017:09:38:26 +0100] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id \'Boomaga_printer-Gray..\' already exists
W [23/Nov/2017:09:38:26 +0100] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id \'Boomaga_printer-CMYK..\' already exists
W [23/Nov/2017:09:38:33 +0100] [Job 298] [Boomaga] Can\'t found active session for user \'root\'.
E [23/Nov/2017:09:38:33 +0100] [Job 298] [Boomaga] Can\'t extract D-Bus bus address for user \"root\" and session \"\"
E [23/Nov/2017:09:38:53 +0100] [cups-deviced] PID 6204 (gutenprint52+usb) stopped with status 1!
W [23/Nov/2017:09:39:40 +0100] [Job 298] [Boomaga] Can\'t found active session for user \'root\'.
E [23/Nov/2017:09:39:40 +0100] [Job 298] [Boomaga] Can\'t extract D-Bus bus address for user \"root\" and session \"\"
E [23/Nov/2017:09:39:44 +0100] [cups-deviced] PID 6388 (gutenprint52+usb) stopped with status 1!
W [23/Nov/2017:09:41:12 +0100] [Job 298] [Boomaga] Can\'t found active session for user \'root\'.
E [23/Nov/2017:09:41:12 +0100] [Job 298] [Boomaga] Can\'t extract D-Bus bus address for user \"root\" and session \"\"
W [23/Nov/2017:09:41:32 +0100] [Job 298] [Boomaga] Can\'t found active session for user \'root\'.
E [23/Nov/2017:09:41:32 +0100] [Job 298] [Boomaga] Can\'t extract D-Bus bus address for user \"root\" and session \"\"
E [23/Nov/2017:09:41:42 +0100] [cups-deviced] PID 6556 (gutenprint52+usb) stopped with status 1!
W [23/Nov/2017:09:42:02 +0100] [Job 298] [Boomaga] Can\'t found active session for user \'root\'.
E [23/Nov/2017:09:42:02 +0100] [Job 298] [Boomaga] Can\'t extract D-Bus bus address for user \"root\" and session \"\"
W [23/Nov/2017:09:44:03 +0100] [Job 299] [Boomaga] Can\'t found active session for user \'root\'.
E [23/Nov/2017:09:44:03 +0100] [Job 299] [Boomaga] Can\'t extract D-Bus bus address for user \"root\" and session \"\"
E [24/Nov/2017:08:13:58 +0100] Missing value on line 2172 of /var/cache/cups/job.cache.
E [24/Nov/2017:08:13:58 +0100] Missing value on line 2291 of /var/cache/cups/job.cache.`

**Comment by SokoloffA** [comment]
Output of `[ktrls@pohl ~]$ sudo /usr/lib/cups/backend/boomaga 666 ktrls "test Boomaga" 1 "" tuscia.csv`
looks good. But you should to send PDF or Postscript file. You can download test PDF files from my repository https://github.com/Boomaga/rendertest
Or try to run as ktrls:
```
[ktrls@pohl ~]$ lpr -P boomaga tuscia.csv 
```
>the answer of your question 1. is that "root" is the user on CUPS with administration access on it
As I understood, you run the test job from the CUPS administarion dialog. Unfortunately it doesn't work. 
How boomaga work:
1. You print a document from your X-session, which is started from normal user.
2. The CUPS server run boomaga backend (/usr/lib/cups/backend/boomaga). The backend gets the user name who sent the print job. 
3. The backend is looking for active X-session and D-Bus address for a user from step 2, and using D-Bus runs boobaga GUI program in the found X-Session.

If you launched as root, then the backend looks for the X-session for root, and does not find it.

**Comment by ktrls** [comment]
Wow! Works.

Thanks you Alexander
