### ISSUE TITLE
Can't install Boomaga in Manjaro

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Boomaga/boomaga#70]
I tried to install Boomaga from AUR in Manjaro, but I didn't find Boomaga in the list of printers after the end of the installation, and I tried to add printer, and choose Boomaga, but I don't know what to write in connection.

![screenshot_20180417_212438](https://user-images.githubusercontent.com/29783425/38892032-6929d814-4286-11e8-8415-929e12375ad2.png)

**Comment by SokoloffA** [comment]
As far as I know Manjaro and Arch Linux doesn't support installation scripts in packages, so you will have to create a printer manually. You can use the following script [scripts/installPrinter.sh](https://github.com/Boomaga/boomaga/raw/master/scripts/installPrinter.sh).

**Comment by SokoloffA** [comment]
Run it as root

**Comment by SokoloffA** [comment]
Do you have files like `~/.cache/boomaga_in_file_*` ?
Are they normal size?
Show me output of `file ~/.cache/boomaga_in_*`

**Comment by ahmed-elsayed2017** [comment]
No such file or directory.

**Comment by ahmed-elsayed2017** [comment]
For more information :

![screenshot_20180422_201415](https://user-images.githubusercontent.com/29783425/39098360-f0b88dca-4669-11e8-9e13-86d69d3f3065.png)

**Comment by ahmed-elsayed2017** [comment]
Yes, I have the .cache directory.

And no output in the terminal for this script : 

sudo journalctl -u cups --since "2018-04-18" |grep -i boomaga

**Comment by SokoloffA** [comment]
1. Check the ownersips  and permissions of the file /usr/lib/cups/backend/boomaga.  It should be root:root rwx------
```
ls -l /usr/lib/cups/backend/boomaga 
-rwx------ 1 root root 13704 мар 22 21:26 /usr/lib/cups/backend/boomaga
```
2. Turn on debug mode in CUPS. [This page](https://wiki.archlinux.org/index.php/CUPS/Troubleshooting) should help you. Try to print and look for messages from the boomaga in the logs.
* In the files in /var/log/cups/
* In the systemd logs through 'journalctl'

**Comment by SokoloffA** [comment]
I now install Manjaro from the scratch in a virtual machine. Executed the following commands:
```
sudo pacman -S  git devtools cmake qt5-tools cups snappy poppler
git clone https://github.com/Boomaga/boomaga.git
mkdir boomaga/build
cd boomaga/build
cmake .. && make && sudo make install
sudo ../scripts/installPrinter.sh
```
And everything works well:
```
echo "Test" | lp -
```
Try to delete the existing virtual printer and install it again
```
sudo ./installPrinter.sh
```

**Comment by ahmed-elsayed2017** [comment]
I removed Boomaga, and compiled it, and it gives me this error :

![screenshot_20180424_233306](https://user-images.githubusercontent.com/29783425/39215394-ed8af2be-4817-11e8-8c3e-72a0d3016031.png)

**Comment by SokoloffA** [comment]
/usr/lib/cups/backend/boomaga must be owned by root.
```
sudo chown root:root /usr/lib/cups/backend/boomaga
```

**Comment by ahmed-elsayed2017** [comment]
Still gives the same error!

**Comment by SokoloffA** [comment]
What does the same error, "has insecure permissions" or "unknown format of input file"?

**Comment by ahmed-elsayed2017** [comment]
![image](https://user-images.githubusercontent.com/29783425/39360563-173ff9f2-4a1f-11e8-96c4-41efa9b2b7c7.png)

**Comment by ahmed-elsayed2017** [comment]
I removed Manjaro. Thanks for your efforst, it's really appreciated.

**Comment by ahmed-elsayed2017** [comment]
I did a fressh installation of Manjaro, and I compiled it as you said before, and it gave me the same error : uknown format of input file.

I checked permissions and this is the result :
![screenshot_ _](https://user-images.githubusercontent.com/29783425/39396161-6f078284-4ae9-11e8-8382-0241c1db0d0b.png)

I get this error when I tried to use this command : 
sudo pacman -S  git devtools cmake qt5-tools cups snappy poppler

![screenshot_ _](https://user-images.githubusercontent.com/29783425/39396176-ca9b0e54-4ae9-11e8-842a-d1529aa8d402.png)

**Comment by SokoloffA** [comment]
About "breaks dependency of the poppler". I don't know, I don't use Manjaro/Arch, please contact to Manjaro community.

About "unknown format of input file". Turn on debug mode in CUPS. [This page](https://wiki.archlinux.org/index.php/CUPS/Troubleshooting) should help you. Try to print and look for messages from the boomaga in the logs.
* In the files in /var/log/cups/
* In the systemd logs through 'journalctl'

**Comment by ahmed-elsayed2017** [comment]
I'm using the Boomaga application directly to open pdf files.

**Comment by ahmed-elsayed2017** [comment]
I tried these commands in terminal : 

cat /var/log/cups/error_log | grep boomaga
journalctl | grep boomaga

and that is the output saved as pdf file

[terminal_output_boomaga.pdf](https://github.com/Boomaga/boomaga/files/1959220/terminal_output_boomaga.pdf)

**Comment by ahmed-elsayed2017** [comment]
Could at least tell me what is Manjaro's release you used that worked without any problem with Boomaga?

**Comment by SokoloffA** [comment]
I checked on Manjaro KDE 17.1.8. But Manjaro is a rolling release distribution, so everything can break at any time.
Now I'm on vacation and I have no way to run Manjaro just now. When I return, I will try to find еру reason of "unknown format" error.

**Comment by SokoloffA** [comment]
I fixed "Unknown format of input file" in the master branch.

**Comment by ahmed-elsayed2017** [comment]
Thank you so much. It is solved.
