### ISSUE TITLE
How do I share your virtual printer on network?

### ISSUE THREAD

**Issue by GreatBahram** [Boomaga/boomaga#77]
Hi,
I want to share Boomaga on network via Samba (or other solution maybe you have) in order let other users use this printer? How do I do that? I tried to do that, but the problem was windows users need a driver for that?
Any suggesions?

**Comment by SokoloffA** [comment]
Unfortunately you can't do that. My program consists of two parts - backend and GUI. When CUPS has formed a document to print, it sends it to backend (/usr/lib/cups/backend/boomaga). Backend looking XWindow session for user which prints the document, and it starts the GUI for this user. So boomaga works only locally.

Unfortunately, there is no version of the program for windows yet. I think about it, but it requires big job, windows has your own print spuller.

**Comment by GreatBahram** [comment]
Thanks @SokoloffA, I think apart from the GUI app that you mentioned, you can share a virtual printer via IPP. But you're right the GUI problem is obstacle here.

Thank you
