### ISSUE TITLE
Missing pstopdf.h breaks compilation from git on Arch Linux

### ISSUE THREAD

**Issue by glitsj16** [Boomaga/boomaga#78]
Hi, I have been building boomaga from git on Arch Linux for quite a while now without issues. Today I noticed that https://github.com/Boomaga/boomaga/commit/a79f0646c5597177d21955199c59e342896295b7 includes `pstopdf.h` in [project.cpp](https://github.com/Boomaga/boomaga/blob/master/src/boomaga/kernel/project.cpp#L36). As this file is not found on my box it causes a fatal error and compilation terminates. After some websearching and using pkgfile I haven't been able to track down in which package this `pstopdf.h` resides. Does anyone here have any ideas on that?

Regards

**Comment by SokoloffA** [comment]
It's my fault. This include got into the commit by mistake.
