### ISSUE TITLE
Error: Form stream has unbalanced q/Q operators (too many q's) 

### ISSUE THREAD

**Issue by zenny** [Boomaga/boomaga#84]
Hi,

Boomaga works perfect except it prints an extra blank start page (when printing double sided as well as in booklet) with error message printed on top of the blank page that reads:

```
**** Warning: glyf ovelaps cmap,
**** Error: Form stream has unbalanced q/Q operators (too many q's)
```
It is installed on Ubuntu trusty from @SokoloffA ppa. Boomaga at v0.9.1-2trusty.

No clue was found online, but similar to https://centosfaq.org/centos/inconsistent-printing-on-centos-7/#comment-58810. Any hints to overcome this issue?

Cheers,
/z

**Comment by SokoloffA** [comment]
Sorry for long silent.

You are using a very, very old version of the program (0.9.1), current is 3.0.0. Unfortunately, Canonical no longer supports Ubuntu Trusty. So I can't build the package for Trusty on the launchpad. 

Try to build a program from sources, this article can be useful. But I'm not sure if Trusty contains the necessary versions of Qt.
