### ISSUE TITLE
Remove "Method 2 – Install via System GUI's" from wiki or push 3.0.0 to main repos

### ISSUE THREAD

**Issue by antonwantstosleep** [Boomaga/boomaga#88]
Linux Mint 19.3 x64 5.3.0-28-generic

1. I tried to install Boomaga by Programm Manager (GUI) - got `1.0.0`. It doesn't work - there is an "error on 4698" and closing window (segfault?). Also It doesn't install any printers - I had to fetch the ppd from your repo.

2. Next I added the ppa and updated Boomaga up to `3.0.0`. This version is ok, works good!

So I think you can remove this [section]( https://github.com/Boomaga/boomaga/wiki/How-to-Install-Boomaga-in-LinuxMint-or-Ubuntu#method-2--install-via-system-guis) from your wiki. Or push `3.0.0` to main repos.. if it`s easy enough to do. Or write a disclaimer about versions.

Thank you!

**Comment by antonwantstosleep** [comment]
Need to admit: your project is awesome! My HP LJ P1102 got a new life with manual duplex on Linux :)

**Comment by SokoloffA** [comment]
Done. Thanks!
