### ISSUE TITLE
Error: Can't extract D-Bus bus address...

### ISSUE THREAD

**Issue by syemvlis** [Boomaga/boomaga#9]
If I print I receive the error "Can't extract D-Bus bus address from /proc files for user 'silvio' (UID: 1000)". How can I fix it?

**Comment by eslavko** [comment]
Hello...
I get similar issue. How to reopen Issue?

**Comment by SokoloffA** [comment]
@eslavko 
What errors do you get in log? What distributive you are using? Do you use systemd?

**Comment by eslavko** [comment]
If I start boomaga from terminal and open individual files I can print them. The problem is that if I print from other program (like libre office) to boomaga printer the file is visible in printer status window but boomaga itself is not oppened.

If I check boomaga printer in system settings I see faulty printer state.
![boomaga](https://cloud.githubusercontent.com/assets/7449672/8314041/214a7f50-19e7-11e5-9567-1d7f14e432b3.png)

From previous post I check DBUS_SESSION_BUS_ADDRESS and dbus deamon. deamon is started and environment variable seems set correctly.

Working on Ubuntu 14.04 /64bit, boomaga 0.7.0 installed from ppa

**Comment by eslavko** [comment]
as far as I know I don't use systemd. (how to check?)

**Comment by SokoloffA** [comment]
Please run the following command in the console:

    cat SOME_PDF_FILE | /usr/lib/boomaga/boomagabackend 123 "title" 1 ""

what output you get?

**Comment by eslavko** [comment]
There is output:
slavko@podstresnik:~$ cat test.pdf | /usr/lib/boomaga/boomagabackend 123 "title" 1 ""
cat: test.pdf: No such file or directory
INFO: [Boomaga] jobId: 123
INFO: [Boomaga] title: title
INFO: [Boomaga] count: 1
INFO: [Boomaga] options: 
DEBUG: [Boomaga] User: slavko
DEBUG: [Boomaga] Uid:  1000
DEBUG: [Boomaga] Home: /home/slavko
DEBUG: [Boomaga] xDisplay: :0
DEBUG: [Boomaga] Scan proc files:
DEBUG: [Boomaga]   * /proc/3700/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2361/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
grep: /proc/3884/environ: No such file or directory
grep: /proc/3884/environ: No such file or directory
DEBUG: [Boomaga]   * /proc/3884/environ     disp='' addr=''
grep: /proc/3883/environ: No such file or directory
grep: /proc/3883/environ: No such file or directory
DEBUG: [Boomaga]   * /proc/3883/environ     disp='' addr=''
grep: /proc/3882/environ: No such file or directory
grep: /proc/3882/environ: No such file or directory
DEBUG: [Boomaga]   * /proc/3882/environ     disp='' addr=''
DEBUG: [Boomaga]   * /proc/3859/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/3841/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
grep: /proc/3840/environ: Permission denied
grep: /proc/3840/environ: Permission denied
DEBUG: [Boomaga]   * /proc/3840/environ     disp='' addr=''
DEBUG: [Boomaga]   * /proc/3833/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/3797/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/3729/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/3700/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2946/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2943/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2930/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2926/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2908/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2902/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2896/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2821/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2813/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2800/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2787/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2778/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2774/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2769/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2754/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2731/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2720/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2700/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2698/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2697/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2694/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2693/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2674/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2673/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2672/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2670/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2667/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2665/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2664/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2662/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2658/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2644/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2634/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2475/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2453/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2418/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2397/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2382/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2380/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2379/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2377/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2372/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2367/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2365/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2361/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2360/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2357/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2353/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2344/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2343/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2342/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2339/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
grep: /proc/2317/environ: Permission denied
grep: /proc/2317/environ: Permission denied
DEBUG: [Boomaga]   * /proc/2317/environ     disp='' addr=''
DEBUG: [Boomaga]   * /proc/2312/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2307/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2296/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2204/environ     disp=':0.0' addr=''
ERROR: [Boomaga] Can't extract D-Bus bus address files for user 'slavko' (UID: 1000)
slavko@podstresnik:~$

**Comment by eslavko** [comment]
Output here:

slavko@podstresnik:~$ cd xx
slavko@podstresnik:~/xx$ cat test.pdf | /usr/lib/boomaga/boomagabackend 123 "title" 1 ""
INFO: [Boomaga] jobId: 123
INFO: [Boomaga] title: title
INFO: [Boomaga] count: 1
INFO: [Boomaga] options: 
DEBUG: [Boomaga] User: slavko
DEBUG: [Boomaga] Uid:  1000
DEBUG: [Boomaga] Home: /home/slavko
DEBUG: [Boomaga] xDisplay: :0
DEBUG: [Boomaga] Scan proc files:
DEBUG: [Boomaga]   * /proc/3700/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2361/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
grep: /proc/4380/environ: No such file or directory
grep: /proc/4380/environ: No such file or directory
DEBUG: [Boomaga]   * /proc/4380/environ     disp='' addr=''
grep: /proc/4379/environ: No such file or directory
grep: /proc/4379/environ: No such file or directory
DEBUG: [Boomaga]   * /proc/4379/environ     disp='' addr=''
grep: /proc/4378/environ: No such file or directory
grep: /proc/4378/environ: No such file or directory
DEBUG: [Boomaga]   * /proc/4378/environ     disp='' addr=''
DEBUG: [Boomaga]   * /proc/4355/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/4342/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
grep: /proc/4341/environ: Permission denied
grep: /proc/4341/environ: Permission denied
DEBUG: [Boomaga]   * /proc/4341/environ     disp='' addr=''
DEBUG: [Boomaga]   * /proc/4333/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/3797/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/3729/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/3700/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2946/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2943/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2930/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2926/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2908/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2902/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2896/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2821/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2813/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2800/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2787/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2778/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2774/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2769/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2754/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2731/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2720/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2700/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2698/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2697/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2694/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2693/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2674/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2673/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2672/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2670/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2667/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2665/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2664/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2662/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2658/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2644/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2634/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2475/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2453/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2418/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2397/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2382/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2380/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2379/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2377/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2372/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0,guid=9498800b99160d0db5bd7e8d558abdc4'
DEBUG: [Boomaga]   * /proc/2367/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2365/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2361/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2360/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2357/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2353/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2344/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2343/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2342/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2339/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
grep: /proc/2317/environ: Permission denied
grep: /proc/2317/environ: Permission denied
DEBUG: [Boomaga]   * /proc/2317/environ     disp='' addr=''
DEBUG: [Boomaga]   * /proc/2312/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2307/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2296/environ     disp=':0.0' addr='unix:abstract=/tmp/dbus-9IFWLkZRg0'
DEBUG: [Boomaga]   * /proc/2204/environ     disp=':0.0' addr=''
ERROR: [Boomaga] Can't extract D-Bus bus address files for user 'slavko' (UID: 1000)
slavko@podstresnik:~/xx$

**Comment by eslavko** [comment]
Property of dbus:
![dbus](https://cloud.githubusercontent.com/assets/7449672/8338607/49f663d0-1ab2-11e5-9768-b2485dc0b329.png)

**Comment by SokoloffA** [comment]
Thanks, I found the problem. Soon I'll  make a fix.

**Comment by eslavko** [comment]
O.K. Will wait...

**Comment by SokoloffA** [comment]
Could you verify the fix? You can apply the changes by using the following command:
```
wget http://rghost.net/download/7nj2Ly2j7/90930291ac733106d8f0747b57afc71b14c0d237/boomagabackend -O boomagabackend && sudo bash -c "cat boomagabackend > /usr/lib/boomaga/boomagabackend"
```

**Comment by eslavko** [comment]
Doesn't work.
When I do print to boomaga before I see job in printer status monitor, after update there are no job in printer status.. 


terminal output:
slavko@podstresnik:~$ cd xx
slavko@podstresnik:~/xx$ cat test.pdf | /usr/lib/boomaga/boomagabackend 123 "title" 1 ""
/usr/lib/boomaga/boomagabackend: line 1: syntax error near unexpected token `newline'
/usr/lib/boomaga/boomagabackend: line 1: `<!DOCTYPE html>'
slavko@podstresnik:~/xx$

**Comment by SokoloffA** [comment]
Oh, the command "wget http://rghost.net/download/..." works incorrectly, it downloads HTML page instead of the script. 
Please download the script via the browser at this [link](http://rghost.net/download/7nj2Ly2j7/90930291ac733106d8f0747b57afc71b14c0d237/boomagabackend), or contact me by mail (sokoloff.a@gmail.com), I will send the script to you.
After that, go to the directory into which you downloaded the script and execute the command:
```
sudo bash -c "cat boomagabackend > /usr/lib/boomaga/boomagabackend"
```

**Comment by eslavko** [comment]
Yep now works...

Thanks...

**Comment by eslavko** [comment]
Hello again...
I got in same situation again. 
But the script is not anymore available.
Can you post it again?
Thanks in advice

**Comment by SokoloffA** [comment]
@eslavko 
In 0.8.0 release I rewrote the boomagabackend to C++, I hope it should to work more correctly no. Try update the program to 0.8.X version.

**Comment by eslavko** [comment]
How to update?
From ppa I get 0.8.0, When try to compile seems that some dependency are not met.

 `slavko@podstresnik:~/boomaga/build$ cmake ..
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:367 (message):
  None of the required 'poppler' found
Call Stack (most recent call first):
  gui/cmake/FindPoppler.cmake:34 (pkg_search_module)
  gui/CMakeLists.txt:194 (find_package)


-- *****************************************************
-- * boomaga ver. 0.8.0
-- *  
-- * Using Qt4, for building with Qt5 use -DUSE_QT5=Yes option.
-- *  
-- * You can change the following directories using cmake options like:
-- * -DCUPS_PPD_DIR=your_path
-- *  
-- *   CUPS_BACKEND_DIR     =  /usr/lib/cups/backend
-- *   CUPS_FILTER_DIR      =  /usr/lib/cups/filter
-- *   CUPS_PPD_DIR         =  /usr/share/ppd/boomaga
-- *   DBUS_MACINE_ID_DIR   =  /var/lib/dbus
-- *   DBUS_SERVICE_DIR     =  /usr/local/share/dbus-1/services
-- *  
-- *  You can change the following options using cmake options:
-- *   INSTANCE_NAME        =  boomaga
-- *   CUPS_BACKEND_URI     =  boomaga:/
-- *   CUPS_BACKEND_INFO    =  Boomaga
-- *   CUPS_BACKEND_MODEL   =  Boomaga printer
-- *   CUPS_BACKEND_DESCRIPTION  = Virtual boomaga printer
-- *   CUPS_BACKEND_MANUFACTURER = Generic
-- *  
-- * For building tests use -DBUILD_TESTS=Yes option.
-- *  
-- *****************************************************
-- Configuring incomplete, errors occurred!
See also "/home/slavko/boomaga/build/CMakeFiles/CMakeOutput.log".
See also "/home/slavko/boomaga/build/CMakeFiles/CMakeError.log".
slavko@podstresnik:~/boomaga/build$ 
`

**Comment by SokoloffA** [comment]
As I can see you are using Ubuntu, so just install 0.8.0 from ppa.

**Comment by SokoloffA** [comment]
@eslavko 
If you want to build from sources, you need to install some dev packages. This article can help you https://github.com/Boomaga/boomaga/wiki/Instalation-from-sources

**Comment by eslavko** [comment]
sudo apt-get install --reinstall boomaga
doesn't help

**Comment by eslavko** [comment]
When I try to install from source following your link I got:
`slavko@podstresnik:~/boomaga/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- *****************************************************
-- * boomaga ver. 0.8.0
-- *  
-- * Using Qt4, for building with Qt5 use -DUSE_QT5=Yes option.
-- *  
-- * You can change the following directories using cmake options like:
-- * -DCUPS_PPD_DIR=your_path
-- *  
-- *   CUPS_BACKEND_DIR     =  /usr/lib/cups/backend
-- *   CUPS_FILTER_DIR      =  /usr/lib/cups/filter
-- *   CUPS_PPD_DIR         =  /usr/share/ppd/boomaga
-- *   DBUS_MACINE_ID_DIR   =  /var/lib/dbus
-- *   DBUS_SERVICE_DIR     =  /usr/local/share/dbus-1/services
-- *  
-- *  You can change the following options using cmake options:
-- *   INSTANCE_NAME        =  boomaga
-- *   CUPS_BACKEND_URI     =  boomaga:/
-- *   CUPS_BACKEND_INFO    =  Boomaga
-- *   CUPS_BACKEND_MODEL   =  Boomaga printer
-- *   CUPS_BACKEND_DESCRIPTION  = Virtual boomaga printer
-- *   CUPS_BACKEND_MANUFACTURER = Generic
-- *  
-- * For building tests use -DBUILD_TESTS=Yes option.
-- *  
-- *****************************************************
-- Configuring done
-- Generating done
-- Build files have been written to: /home/slavko/boomaga/build
slavko@podstresnik:~/boomaga/build$ ^C
`

**Comment by SokoloffA** [comment]
> sudo apt-get install --reinstall boomaga
doesn't help

verry strange
show me output of
```
ls -l /usr/lib/cups/backend/boomaga
sudo file --mime-type /usr/lib/cups/backend/boomaga
```

**Comment by SokoloffA** [comment]
and check what version of boomaga is installed

**Comment by eslavko** [comment]
slavko@podstresnik:~$ ls -l /usr/lib/cups/backend/boomaga
-rwx------ 1 root root 10328 sep  5 19:19 /usr/lib/cups/backend/boomaga
slavko@podstresnik:~$ sudo file --mime-type /usr/lib/cups/backend/boomaga
[sudo] password for slavko: 
/usr/lib/cups/backend/boomaga: application/x-executable
slavko@podstresnik:~$ 

Version from boomaga gui: 0.8.0

**Comment by eslavko** [comment]
..and printer gui:
![screenshot from 2016-09-24 13 44 03](https://cloud.githubusercontent.com/assets/7449672/18808252/23cf488e-825d-11e6-9a88-bb84011de1a9.png)
